#ifndef FRAMEHOOK_H_
#define FRAMEHOOK_H_

/*Framehookに渡されるオプション用の定義*/

#define FRAMEHOOK_OPT_DATA_USER		"--data-user:"
#define FRAMEHOOK_OPT_DATA_USER_LEN	strlen(FRAMEHOOK_OPT_DATA_USER)

#define FRAMEHOOK_OPT_DATA_OWNER		"--data-owner:"
#define FRAMEHOOK_OPT_DATA_OWNER_LEN	strlen(FRAMEHOOK_OPT_DATA_OWNER)

#define FRAMEHOOK_OPT_DATA_OPTIONAL	"--data-optional:"
#define FRAMEHOOK_OPT_DATA_OPTIONAL_LEN	strlen(FRAMEHOOK_OPT_DATA_OPTIONAL)

#define FRAMEHOOK_OPT_FONT		"--font:"
#define FRAMEHOOK_OPT_FONT_LEN	strlen(FRAMEHOOK_OPT_FONT)

#define FRAMEHOOK_OPT_FONTINDEX		"--font-index:"
#define FRAMEHOOK_OPT_FONTINDEX_LEN	strlen(FRAMEHOOK_OPT_FONTINDEX)

#define FRAMEHOOK_OPT_FONTSIZE		"--enable-fix-font-size"
#define FRAMEHOOK_OPT_FONTSIZE_LEN	strlen(FRAMEHOOK_OPT_FONTSIZE)

#define FRAMEHOOK_OPT_SHADOW		"--shadow:"
#define FRAMEHOOK_OPT_SHADOW_LEN	strlen(FRAMEHOOK_OPT_SHADOW)

#define FRAMEHOOK_OPT_SHOW_USER		"--show-user:"
#define FRAMEHOOK_OPT_SHOW_USER_LEN	strlen(FRAMEHOOK_OPT_SHOW_USER)

#define FRAMEHOOK_OPT_SHOW_OWNER		"--show-owner:"
#define FRAMEHOOK_OPT_SHOW_OWNER_LEN	strlen(FRAMEHOOK_OPT_SHOW_OWNER)

#define FRAMEHOOK_OPT_SHOW_OPTIONAL 	"--show-optional:"
#define FRAMEHOOK_OPT_SHOW_OPTIONAL_LEN	strlen(FRAMEHOOK_OPT_SHOW_OPTIONAL)

#define FRAMEHOOK_OPT_SHOW_VIDEO		"--enable-show-video"
#define FRAMEHOOK_OPT_SHOW_VIDEO_LEN	strlen(FRAMEHOOK_OPT_SHOW_VIDEO)

#define FRAMEHOOK_OPT_OPAQUE_COMMENT		"--enable-opaque-comment"
#define FRAMEHOOK_OPT_OPAQUE_COMMENT_LEN	strlen(FRAMEHOOK_OPT_OPAQUE_COMMENT)

#define FRAMEHOOK_OPT_OPTIONAL_TRANSLUCENT	"--optional-translucent"
#define FRAMEHOOK_OPT_OPTIONAL_TRANSLUCENT_LEN	strlen(FRAMEHOOK_OPT_OPTIONAL_TRANSLUCENT)

#define FRAMEHOOK_OPT_VIDEO_LENGTH	"--video-length:"
#define FRAMEHOOK_OPT_VIDEO_LENGTH_LEN	strlen(FRAMEHOOK_OPT_VIDEO_LENGTH)

#define FRAMEHOOK_OPT_FONT_HEIGHT_FIX "--font-height-fix-ratio:"
#define FRAMEHOOK_OPT_FONT_HEIGHT_FIX_LEN strlen(FRAMEHOOK_OPT_FONT_HEIGHT_FIX)

#define FRAMEHOOK_OPT_ASPECT_MODE		"--aspect-mode:"
#define FRAMEHOOK_OPT_ASPECT_MODE_LEN	strlen(FRAMEHOOK_OPT_ASPECT_MODE)

#define FRAMEHOOK_OPT_LIMIT_WIDTH	"--limit-width:"
#define FRAMEHOOK_OPT_LIMIT_WIDTH_LEN	strlen(FRAMEHOOK_OPT_LIMIT_WIDTH)

#define FRAMEHOOK_OPT_LIMIT_HEIGHT	"--limit-height:"
#define FRAMEHOOK_OPT_LIMIT_HEIGHT_LEN	strlen(FRAMEHOOK_OPT_LIMIT_HEIGHT)

#define FRAMEHOOK_OPT_FIXED_FONT_SIZE	"--fixed-font-size:"
#define FRAMEHOOK_OPT_FIXED_FONT_SIZE_LEN	strlen(FRAMEHOOK_OPT_FIXED_FONT_SIZE)

#define FRAMEHOOK_OPT_TARGET_SIZE	"--target-size:"
#define FRAMEHOOK_OPT_TARGET_SIZE_LEN	strlen(FRAMEHOOK_OPT_TARGET_SIZE)

#endif /*FRAMEHOOK_H_*/
