#ifndef FRAMEHOOK_H_
#define FRAMEHOOK_H_

/*Framehookに渡されるオプション用の定義*/

#define FRAMEHOOK_OPT_DATA_USER		"--data-user:"
#define FRAMEHOOK_OPT_DATA_USER_LEN	strlen(FRAMEHOOK_OPT_DATA_USER)

#define FRAMEHOOK_OPT_DATA_OWNER		"--data-owner:"
#define FRAMEHOOK_OPT_DATA_OWNER_LEN	strlen(FRAMEHOOK_OPT_DATA_OWNER)

#define FRAMEHOOK_OPT_FONT		"--font:"
#define FRAMEHOOK_OPT_FONT_LEN	strlen(FRAMEHOOK_OPT_FONT)

#define FRAMEHOOK_OPT_FONTINDEX		"--font-index:"
#define FRAMEHOOK_OPT_FONTINDEX_LEN	strlen(FRAMEHOOK_OPT_FONTINDEX)

#define FRAMEHOOK_OPT_FONTSIZE		"--enable-fix-font-size"
#define FRAMEHOOK_OPT_FONTSIZE_LEN	strlen(FRAMEHOOK_OPT_FONTSIZE)

#define FRAMEHOOK_OPT_SHADOW		"--shadow:"
#define FRAMEHOOK_OPT_SHADOW_LEN	strlen(FRAMEHOOK_OPT_SHADOW)

#define FRAMEHOOK_OPT_SHOW_USER		"--show-user:"
#define FRAMEHOOK_OPT_SHOW_USER_LEN	strlen(FRAMEHOOK_OPT_SHOW_USER)

#define FRAMEHOOK_OPT_SHOW_OWNER		"--show-owner:"
#define FRAMEHOOK_OPT_SHOW_OWNER_LEN	strlen(FRAMEHOOK_OPT_SHOW_OWNER)

#define FRAMEHOOK_OPT_SHOW_VIDEO		"--enable-show-video"
#define FRAMEHOOK_OPT_SHOW_VIDEO_LEN	strlen(FRAMEHOOK_OPT_SHOW_VIDEO)

#define FRAMEHOOK_OPT_OPAQUE_COMMENT		"--enable-opaque-comment"
#define FRAMEHOOK_OPT_OPAQUE_COMMENT_LEN	strlen(FRAMEHOOK_OPT_OPAQUE_COMMENT)

#endif /*FRAMEHOOK_H_*/
